### ISSUE TITLE
 package ‘fs’ does not have a namespace

### ISSUE THREAD

**Issue by nujcharee** [EmilHvitfeldt/textdata#24]
When install textdata package via remotes::install_github last night I got an error message below when trying to load the library. Please could you kindly advice? Thank you so much.

Error: package or namespace load failed for ‘textdata’:
 package ‘fs’ does not have a namespace

**Comment by EmilHvitfeldt** [comment]
Hello!

It looks like you might have a a problem with `fs`. could you try to use `install.packages("fs")` for me before `remotes::install_github("EmilHvitfeldt/textdata")` and tell me what happens?

Screenshots or copy pasted messages would be awesome

**Comment by nujcharee** [comment]
hi there, thank you for your advice, I did all of that but I discovered that the issue was from the fact that I have more than multiple locations for libraries... all sorted now if I explicitly load my library from a specific location.
